### PR TITLE
Quick refresh for Debian jessie

### PR DESCRIPTION
**Pull request by janbraiins**
Hi Bryan,

just wondering if you care to accept the below changes. Except for switching to jessie, I believe, the remaining 3 changes should be non-conflicting with your original intention.

Cheers,

Jan

### CODE REVIEW

**Comment by bryanhong** [comment]
Hi Jan, 

Thanks for the proposals! I took a look at your proposed changes, unfortunately, there is more that would need to change here: https://github.com/bryanhong/docker-aptly/blob/master/assets/update_mirror.sh

With your changes we'd build a working aptly container in Debian, but I wanted to take it one step further with that script to make it "easy" to create a basic mirror for folks that are new or uninitiated to Aptly. If this is important to you, I could create a branch for Debian and we can work on that or we can point folks to your repo if you have something built already. Thoughts?

Thanks, 

Bryan

**Comment by janbraiins** [comment]
Hi Bryan,

the Debian branch is a good option I have no problem rebasing it
anytime you make some changes. The master branch can stay on Ubuntu as
that may be the preferred option for new comers.

As of the rest of the changes, all of them I find pretty important as
they improve the user experience - we have multiple aliases for the
same physical repo (not sure if you consider the host name quoting as a
hack..) and public key publishing is also very convenient for the user.

Let me know,

Jan

On Mon, 22 May 2017 22:55:01 -0700
"Bryan J. Hong" <notifications@github.com> wrote:

> Hi Jan, 
> 
> Thanks for the proposals! I took a look at your proposed changes,
> unfortunately, there is more that would need to change here:
> https://github.com/bryanhong/docker-aptly/blob/master/assets/update_mirror.sh
> 
> With your changes we'd build a working aptly container in Debian, but
> I wanted to take it one step further with that script to make it
> "easy" to create a basic mirror for folks that are new or uninitiated
> to Aptly. If this is important to you, I could create a branch for
> Debian and we can work on that or we can point folks to your repo if
> you have something built already. Thoughts?
> 
> Thanks, 
> 
> Bryan
> 



-- 
CEO Braiins Systems | Slushpool.com

**Comment by bryanhong** [comment]
Hi Jan, 

I went ahead and incorporated a couple of your changes into master. I also created a debian_option branch, I think it'll be easier to merge it to master rather than maintain 2 branches. Here's the PR: https://github.com/bryanhong/docker-aptly/pull/2 let me know if you have any suggestions or thoughts. 

Bryan

**Comment by janbraiins** [comment]
The debian_option branch looks fine to me, just wondering, would you consider: https://github.com/bryanhong/docker-aptly/pull/1/commits/86b39fdebbad1983776d3f474b92ef06a69b8378 to be included too? Publishing the key makes the use also much smoother

**Comment by bryanhong** [comment]
I address that in two places, [here](https://github.com/bryanhong/docker-aptly/blob/debian_option/assets/update_mirror/update_mirror_debian.sh#L69-L72) and [here](https://github.com/bryanhong/docker-aptly/blob/debian_option/assets/startup.sh#L11-L14). I went this route to export just the signing key in TXT format and to serve it from the public directory.

**Comment by janbraiins** [comment]
On Wed, 24 May 2017 07:34:24 -0700
"Bryan J. Hong" <notifications@github.com> wrote:

> I address that in two places,
> [here](https://github.com/bryanhong/docker-aptly/blob/debian_option/assets/update_mirror/update_mirror_debian.sh#L69-L72)
> and
> [here](https://github.com/bryanhong/docker-aptly/blob/debian_option/assets/startup.sh#L11-L14).
> I went this route to export just the signing key in TXT format and to
> serve it from the public directory. 
> 
That looks good to me, I am sorry, I didn't notice this earlier.
Somehow I felt it would be easier to create an alias in nginx point to
the root of the repository. This is perfectly fine, thought.

I think we have now covered all the changes. Thank you for quick and
efficient way of sorting this out.

**Comment by bryanhong** [comment]
No worries, thanks so much for contributing these improvements, much appreciated!

**Pull request closed without merging**
